### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leapdao-integ-tests#7]
# Bounty :

## Scenarios
- deposit - transfer - exit
- deposit - consolidate - exit
- deposit - exit - try transfer
- contract upgrade
- deposit - transfer - change epoch Length - exit
- define simple tests for slots in poaOperator
  - add
  - remove
- synchronicity tests ?? 

## Deliverables
- code

## Gain for the project
- Prevent regression.

----
gardener: @johannbarbie | 0%
worker: @eshavkun | 80%
reviewer:  @troggy  | 20%

**Comment by johannbarbie** [comment]
more ideas: deposit, transfer, exit, exit priorities, finalize exits, fast exits, governance params change, governance change, contract upgrades etc

**Comment by eshavkun** [comment]
> more ideas: deposit, transfer, exit, exit priorities, finalize exits, fast exits, governance params change, governance change, contract upgrades etc

Sounds like new bounty to me :) Especially with upgrade and governance stuff the scope is much bigger than original bounty. Or may be even a role of integration tests maintainer :) 'Cos after the basic tests are done and kinda framework is created, we can go on with a lot more tests. Smth for acceptance checklist?
